langauge: generic
dist: trusty
sudo: required

branches:
  only:
  - master

oservices:
  - docker

before_install:
  - git clone --depth=1 https://github.com/radare/radare2
  - cd radare2 && sh sys/install.sh

script:
  - ./configure
  - make
  - make install
