langauge: generic
dist: trusty
sudo: required

branches:
  only:
  - master

oservices:
  - docker

before_install:
  - git clone --depth=1 https://github.com/radare/radare2
  - cd radare2 && ./configure --prefix=/usr && make -j4 && sudo make install

script:
  - ./configure
  - make
  - make install
