langauge: generic
dist: trusty
sudo: required

branches:
  only:
  - master

matrix:
  fast_finish: true
  include:
    - os: linux
      name: Debian
      dist: trusty
    - os: linux
      name: Build

oservices:
  - docker

before_script:
  - git clone --depth=1 https://github.com/radare/radare2 > /dev/null
  - cd radare2 && sys/install.sh /usr > /dev/null
#  - cd radare2 && ./configure --prefix=/usr > /dev/null && make -j4 > /dev/null && sudo make install > /dev/null

script:
  - |
    case "$TRAVIS_JOB_NAME" in
    Build)
      ./configure --prefix=/usr
      make
      sudo make install
      # r2 -qcq frida://0
      ;;
    Debian)
      make deb
      wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
      compgen -G "dist/debian/*.deb" > /dev/null && bash upload.sh dist/debian/*.deb
      #  - compgen -G "/tmp/*.pkg" > /dev/null && bash upload.sh /tmp/*.pkg
      ;;
    esac

after_success:
